config/routes.rb
Rails.application.routes.draw do
  get 'players/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :games, param: :number
  get "search" => "games#search"
  resources :players, param: :name
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default
  .container
    .row.nav-row
      // .col-md-6.col-md-offset-3
      // .navbar-header
      %a.navbar-brand.logo{:href => "/"}
        = ["🐑","🌲","🌾","⛰️","🎲"].sample
      %a.navbar-brand.logo-text{:href => "/"}
        Federation Catan
      %ul.nav.navbar-nav
        %li.active
          %a{:href => "#"}
            = "Game #{params[:number]}"
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Players
            %i.fa.fa-caret-down
          %ul.dropdown-menu{:role => "menu"}
            - Player.all.order(:name).each do |p|
              %li= link_to p.name, player_path(p.name.downcase)
              %li.divider
        = form_tag search_path, :class => "navbar-form navbar-left", :method => :get do
          = text_field_tag :number, nil, class: "form-control", placeholder: "Game #", autocomplete: "off"
        - unless flash[:alert].blank?
          %li.alert.alert-danger
            = flash[:alert]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      
      <%= yield %>
    </div>
    
  </body>
</html>